### ISSUE TITLE
Build fails while applying patches

### ISSUE THREAD

**Issue by ghost** [droidapps/pdfreader4Android#2]
Running the build-native.sh throws following errors:

```
copying mupdf
patching mupdf
patching file jni/mupdf/fitz/fitz.h
Hunk #1 succeeded at 24 with fuzz 1.
patching file jni/mupdf-apv/fitz/apv_doc_document.c (read from jni/mupdf/fitz/doc_document.c)
patching file jni/mupdf-apv/pdf/apv_pdf_cmap_table.c (read from jni/mupdf/pdf/pdf_cmap_table.c)
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file jni/mupdf-apv/pdf/apv_pdf_cmap_table.c.rej
patching file jni/mupdf-apv/pdf/apv_pdf_fontfile.c (read from jni/mupdf/pdf/pdf_fontfile.c)
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file jni/mupdf-apv/pdf/apv_pdf_fontfile.c.rej
```

Does the same thing work for you?

**Comment by ghost** [comment]
Files are copied. Still fails with recent commit. I had @mvdan try it and it fials for him, too. Does the build work at your end? If so, I assume you are running Windows? I think i will have a look at the patches themselves later next week...

**Comment by droidapps** [comment]
I have patched the files. They are in MASTER. 
You just have to run `ndk-build`

**Comment by ghost** [comment]
Sorry, I got swamped by other apps. Will try to work on it this week.

**Comment by droidapps** [comment]
I have fixed all errors. [Release](https://github.com/droidapps/pdfreader4Android/releases/tag/0.4.0-patched)
The files in MASTER are already patched. 
Please let me know if you want unpatched files.

**Comment by droidapps** [comment]
I have fixed all errors.
Please try to build (ndk-build). It should work now.

https://github.com/droidapps/pdfreader4Android/releases/tag/0.4.0-patched

**Comment by ghost** [comment]
Sorry I kept you waiting. Thanks for your patience and -- obviously -- for the app. Enabled with https://gitlab.com/fdroid/fdroiddata/commit/319ccdf08133003841da2a4402889f81da1cfe3d
